// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seguradora.Infrastructure;

#nullable disable

namespace Seguradora.Infrastructure.Migrations
{
    [DbContext(typeof(SeguradoraDBContext))]
    [Migration("20250716190315_AjustesSeguradoraDB")]
    partial class AjustesSeguradoraDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Seguradora.Domain.Apolice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeguradoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoId");

                    b.ToTable("Apolices");
                });

            modelBuilder.Entity("Seguradora.Domain.Artefato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApoliceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.ToTable("Artefatos");
                });

            modelBuilder.Entity("Seguradora.Domain.Segurado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Segurados");
                });

            modelBuilder.Entity("Seguradora.Domain.Apolice", b =>
                {
                    b.HasOne("Seguradora.Domain.Segurado", "Segurado")
                        .WithMany("Apolices")
                        .HasForeignKey("SeguradoId");

                    b.Navigation("Segurado");
                });

            modelBuilder.Entity("Seguradora.Domain.Artefato", b =>
                {
                    b.HasOne("Seguradora.Domain.Apolice", "Apolice")
                        .WithMany("Artefatos")
                        .HasForeignKey("ApoliceId");

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("Seguradora.Domain.Apolice", b =>
                {
                    b.Navigation("Artefatos");
                });

            modelBuilder.Entity("Seguradora.Domain.Segurado", b =>
                {
                    b.Navigation("Apolices");
                });
#pragma warning restore 612, 618
        }
    }
}
